import {launchBackgroundReader} from './background-reader.mjs';
import {assertNoDockApp} from './mac-app-policy.mjs';
import fs from 'node:fs';
import path from 'node:path';
const output=path.resolve('work/qa-native');fs.mkdirSync(output,{recursive:true});
const executablePath=path.resolve('dist-electron/mac-arm64/Get It Jacob.app/Contents/MacOS/Get It Jacob');
const env={...process.env,GETIT_DATA_DIR:path.resolve('work/native-data')};
delete env.ELECTRON_RUN_AS_NODE;delete env.CODEX_BINARY_PATH;
let app;
try {
 app=await launchBackgroundReader({executablePath,env,timeout:60000});
 const page=await app.firstWindow({timeout:60000});
 await page.waitForURL('http://127.0.0.1:**',{timeout:60000});
 await page.locator('input[type=file]').waitFor({state:'attached'});
 const dockChecks=[assertNoDockApp(executablePath)];
 await page.screenshot({path:path.join(output,'01-home.png')});
 console.log('NATIVE OPEN',page.url());
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const start=Date.now();await page.locator('input[type=file]').setInputFiles('work/lecture-test.pdf');
 await Promise.race([page.waitForURL('**/viewer/**',{timeout:360000}), page.getByRole('alert').filter({hasText:'La préparation n’a pas pu se terminer'}).waitFor({state:'visible',timeout:360000}).then(async()=>{throw Error(await page.getByRole('alert').filter({hasText:'La préparation n’a pas pu se terminer'}).innerText());})]);
 const preparationMs=Date.now()-start;
 const docId=new URL(page.url()).pathname.split('/').pop();
 console.log('NATIVE PREPARED',docId,Date.now()-start);
 await page.locator('.pdf-selectable-text span').first().waitFor({state:'attached'});
 await page.screenshot({path:path.join(output,'02-reader.png')});
 const base=new URL(page.url()).origin;
 const chats=await(await fetch(base+'/api/chat/'+docId)).json();
 const chat=chats.chats[0];if(!chat.codexThreadId)throw Error('Missing seeded context');
 await page.getByRole('button',{name:'Jump to page',exact:true}).click();
 await page.getByRole('textbox',{name:'Go to page',exact:true}).fill('3');
 await page.getByRole('textbox',{name:'Go to page',exact:true}).press('Enter');
 await page.getByText('Contexte : page 3 du PDF',{exact:true}).waitFor();
 await page.getByPlaceholder('Que souhaitez-vous comprendre ?').fill('Quel est le mot de contrôle et la capacité confirmée ?');
 const t=Date.now();const responsePromise=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/chat/'+docId)&&r.request().postDataJSON()?.action==='send');
 await page.getByPlaceholder('Que souhaitez-vous comprendre ?').press('Enter');
 const response=await responsePromise;
 if(response.request().postDataJSON().pageIndex!==2)throw Error('Wrong viewed page in UI request');
 const raw=await response.text();const events=raw.split('\n').filter(l=>l.startsWith('data:')).map(l=>JSON.parse(l.slice(5)));
 const done=events.find(e=>e.type==='done');if(!done)throw Error(raw);
 const text=events.filter(e=>e.type==='text').at(-1)?.text??'';
 if(!text.includes('47')||!text.toUpperCase().includes('ORION'))throw Error('Wrong scanned context: '+text);
 dockChecks.push(assertNoDockApp(executablePath));
 console.log('NATIVE CHAT PASS',Date.now()-t,text);
 await page.getByText('ORION',{exact:false}).first().waitFor();
 await page.waitForTimeout(500);
 await page.screenshot({path:path.join(output,'03-chat.png')});
 await app.close();app=null;
 app=await launchBackgroundReader({executablePath,env,timeout:60000});
 const second=await app.firstWindow();await second.waitForURL('http://127.0.0.1:**',{timeout:60000});
 const origin=new URL(second.url()).origin;
 const post=[];second.on('request',r=>{if(r.method()==='POST'&&!r.url().endsWith('/touch'))post.push(r.url());});
 await second.goto(origin+'/viewer/'+docId);await second.getByText('ORION',{exact:false}).first().waitFor();
 await second.locator('.pdf-selectable-text span').first().waitFor({state:'attached'});
 await second.waitForTimeout(2500);
 await second.screenshot({path:path.join(output,'04-restarted.png')});if(post.length)throw Error('Spontaneous POST on reopening '+post.join());
 fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({pass:true,docId,preparationMs,errors,text,automaticPostsOnReopen:post,dockChecks},null,2));
 if(errors.length)throw Error(errors.join('\n'));
 console.log('NATIVE RESTART PASS');
} finally {await app?.close();}
