// Modified September 2026 for Get It Jacob; see NOTICE.
/** Local attachment/route tests. Synthetic documents only; no windows or AI calls. */
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { createCanvas } from "@napi-rs/canvas";
import type { DocumentAIInput, DocumentAIServer } from "../lib/document-ai";
import type { CaptureAttachment } from "../lib/capture-types";

async function main() {
  fs.mkdirSync("work", { recursive: true });
  process.env.GETIT_DATA_DIR = fs.mkdtempSync(path.resolve("work/capture-test-"));
  const { saveDoc } = await import("../lib/store");
  const { docDir, pdfPath } = await import("../lib/paths");
  const { loadWorkContext } = await import("../lib/work-context");
  const { resolveCapture } = await import("../lib/captures");
  const upload = await import("../app/api/captures/[docId]/route");
  const imageRoute = await import("../app/api/captures/[docId]/[captureId]/route");
  const chatRoute = await import("../app/api/chat/[docId]/route");
  const calls: DocumentAIInput[] = [];
  let failNext = false;
  globalThis.__getItDocumentAI = { async run(input: DocumentAIInput) {
    calls.push(input);
    if (failNext) { failNext = false; throw new Error("Transient test failure"); }
    return { text: "Graphiques reçus.", threadId: input.threadId ?? `test-thread-${calls.length}` };
  } } as unknown as DocumentAIServer;
  const docId = "capture-document-a";
  const otherId = "capture-document-b";
  for (const id of [docId, otherId]) {
    saveDoc({ id, filename: "synthetic.pdf", uploadedAt: Date.now(), numPages: 3, pdfUrl: `/api/pdf/${id}`, extracted: { numPages: 3, pages: [0, 1, 2].map(pageIndex => ({ pageIndex, text: `Original page ${pageIndex + 1}`, width: 500, height: 700, items: [] })) } });
    fs.writeFileSync(pdfPath(id), "synthetic-source");
    fs.mkdirSync(path.join(docDir(id), "pages"));
    fs.writeFileSync(path.join(docDir(id), "pages/page-3.jpg"), "synthetic-page-image");
    fs.writeFileSync(path.join(docDir(id), "preparation.json"), JSON.stringify({ version: 2, status: "ready", totalPages: 3, completedPages: 3, visualPages: [2], pages: [0, 1, 2].map(pageIndex => ({ pageIndex, notes: "Local text", kind: pageIndex === 2 ? "visual" : "text" })), updatedAt: Date.now() }));
  }
  const request = (body: unknown) => new Request("http://localhost/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const context = (id = docId) => ({ params: Promise.resolve({ docId: id }) });
  const canvas = createCanvas(240, 120);
  const drawing = canvas.getContext("2d");
  drawing.fillStyle = "white"; drawing.fillRect(0, 0, 240, 120);
  drawing.fillStyle = "blue"; drawing.fillRect(30, 50, 80, 40);
  const png = canvas.toBuffer("image/png");
  const jpeg = canvas.toBuffer("image/jpeg", 90);
  const source = { dataUrl: `data:image/png;base64,${png.toString("base64")}`, pageIndex: 0, width: 240, height: 120 };
  const firstResponse = await upload.POST(request(source), context());
  assert.equal(firstResponse.status, 201);
  const first = (await firstResponse.json()).capture as CaptureAttachment;
  assert.equal(first.name, "Capture d’écran 1");
  assert.equal(first.pageIndex, 0);
  assert.deepEqual([first.width, first.height], [240, 120]);
  const concurrent = await Promise.all([1, 2].map(pageIndex => upload.POST(request({ ...source, pageIndex, dataUrl: `data:image/jpeg;base64,${jpeg.toString("base64")}` }), context()).then(response => response.json())));
  const [second, third] = concurrent.map(result => result.capture as CaptureAttachment);
  assert.deepEqual([second.name, third.name].sort(), ["Capture d’écran 2", "Capture d’écran 3"]);
  assert.equal(calls.length, 0, "uploading and accumulating captures never invokes AI");
  assert.equal(loadWorkContext(docId).chats.length, 0, "upload does not create a chat or user message");
  const fetchImage = (captureId: string, id = docId) => imageRoute.GET(new Request("http://localhost/"), { params: Promise.resolve({ docId: id, captureId }) });
  const fetched = await fetchImage(first.id);
  assert.equal(fetched.status, 200);
  assert.equal(fetched.headers.get("Content-Type"), "image/png");
  assert.equal(Buffer.from(await fetched.arrayBuffer()).subarray(0, 8).toString("hex"), "89504e470d0a1a0a");
  assert.equal((await fetchImage(second.id)).headers.get("Content-Type"), "image/jpeg");
  assert.equal((await fetchImage(first.id, otherId)).status, 404, "cross-document capture cannot be fetched");
  for (const badId of ["../../meta.json", "%2e%2e%2fsource.pdf", "00000000-0000-0000-0000-000000000000"]) assert.equal((await fetchImage(badId)).status, 404);
  const invalidSources = [null, [], {}, { ...source, pageIndex: -1 }, { ...source, pageIndex: 3 }, { ...source, width: 239 }, { ...source, height: 9000 }, { ...source, dataUrl: "data:image/svg+xml;base64,PHN2Zz4=" }, { ...source, dataUrl: "data:image/png;base64,aGVsbG8=" }, { ...source, dataUrl: `data:image/png;base64,${png.subarray(0, 33).toString("base64")}` }, { ...source, dataUrl: `data:image/jpeg;base64,${png.toString("base64")}` }];
  for (const invalid of invalidSources) assert.equal((await upload.POST(request(invalid), context())).status, 400, JSON.stringify(invalid));
  const hugeHeader = Buffer.from(png); hugeHeader.writeUInt32BE(1_000_000, 16);
  assert.equal((await upload.POST(request({ ...source, dataUrl: `data:image/png;base64,${hugeHeader.toString("base64")}` }), context())).status, 400);
  assert.equal((await upload.POST(request({ ...source, dataUrl: "x".repeat(17 * 1024 * 1024) }), context())).status, 413);
  assert.equal((await upload.POST(request(source), context("../outside"))).status, 404);
  // Metadata/path supplied by the caller is ignored; persisted records are authoritative.
  const fourth = (await (await upload.POST(request({ ...source, name: "overwrite", id: "../bad", path: "/etc/passwd" }), context())).json()).capture as CaptureAttachment;
  assert.equal(fourth.name, "Capture d’écran 4");
  globalThis.__getitStore?.clear();
  assert.deepEqual(resolveCapture(docId, first.id).capture, first, "capture metadata survives cache reset and disk reload");
  const postChat = (body: unknown) => chatRoute.POST(request(body), context());
  const chatId = (await (await postChat({ action: "create" })).json()).chat.id;
  const payload = { action: "send", chatId, requestId: "12345678-1234-1234-1234-123456789abc", message: "Compare ces deux graphiques", pageIndex: 2, captureIds: [first.id, second.id] };
  for (const ids of [["../outside"], [first.id, first.id], "bad", [false], Array.from({ length: 25 }, (_, i) => `${i}`)]) assert.notEqual((await postChat({ ...payload, captureIds: ids })).status, 200);
  const otherCapture = (await (await upload.POST(request(source), context(otherId))).json()).capture;
  assert.equal((await postChat({ ...payload, captureIds: [otherCapture.id] })).status, 404);
  assert.equal(calls.length, 0, "invalid requests never invoke AI");
  const events = async (body: unknown) => (await (await postChat(body)).text()).split("\n\n").filter(line => line.startsWith("data: ")).map(line => JSON.parse(line.slice(6)));
  assert.equal((await events(payload)).at(-1).type, "done");
  assert.equal(calls.length, 1);
  const recovered = await events(payload);
  assert.equal(recovered.at(-1).type, "done");
  assert.equal(recovered.at(-1).timing.replayed, true);
  assert.equal(calls.length, 1, "lost SSE done retry recovers persisted response without a second AI call");
  assert.equal(loadWorkContext(docId).chats[0].messages.length, 2);
  for (const mismatch of [{ message: "Different" }, { pageIndex: 1 }, { captureIds: [first.id] }, { selection: "different" }]) assert.equal((await postChat({ ...payload, ...mismatch })).status, 409, "request id cannot be reused for different content");
  for (const requestId of ["bad", 12, "../outside"]) assert.equal((await postChat({ ...payload, requestId })).status, 400);
  assert.equal(calls.length, 1);
  assert.deepEqual(calls[0].imagePaths, [path.join(docDir(docId), "pages/page-3.jpg"), resolveCapture(docId, first.id).path, resolveCapture(docId, second.id).path]);
  assert.match(calls[0].input, /Image 2: Capture d’écran 1.*PDF page 1/);
  assert.match(calls[0].input, new RegExp(`Image 3: ${second.name}.*PDF page ${second.pageIndex + 1}`));
  assert.match(calls[0].input, /Compare ces deux graphiques/);
  assert.deepEqual(loadWorkContext(docId).chats[0].messages[0].captures, [first, second]);
  assert.equal((await events({ ...payload, requestId: "12345678-1234-1234-1234-123456789abd", message: "Et celui-ci ?", captureIds: [third.id] })).at(-1).type, "done");
  assert.equal(calls[1].threadId, "test-thread-1");
  assert.deepEqual(calls[1].imagePaths, [resolveCapture(docId, third.id).path], "warm thread receives new crops even when the whole document is already seeded");
  assert.doesNotMatch(calls[1].input, /Original page 1/);
  assert.match(calls[1].input, new RegExp(`Image 1: ${third.name}`));
  failNext = true;
  assert.equal((await events({ ...payload, requestId: "12345678-1234-1234-1234-123456789abe", captureIds: [fourth.id] })).at(-1).type, "error");
  assert.equal(loadWorkContext(docId).chats[0].messages.length, 4, "failed request leaves no orphaned user message");
  assert.equal((await events({ ...payload, requestId: "12345678-1234-1234-1234-123456789abe", captureIds: [fourth.id] })).at(-1).type, "done");
  const retry = calls[3];
  assert.equal(retry.threadId, undefined);
  assert.equal(retry.imagePaths?.length, 5, "migration restores original PDF image, all three historical crops and new crop");
  assert.match(retry.input, /PREVIOUS CONVERSATION/);
  assert.match(retry.input, /CAPTURES IN THAT MESSAGE: Capture d’écran 1/);
  assert.match(retry.input, /Image 5: Capture d’écran 4/);
  assert.match(retry.input, /CURRENT USER CAPTURES:\nCapture d’écran 4/);
  assert.equal(loadWorkContext(docId).chats[0].messages.length, 6);
  assert.equal((await events({ ...payload, requestId: undefined, message: "Merci", captureIds: [] })).at(-1).type, "done");
  assert.deepEqual(calls[4].imagePaths, [], "later text-only turn does not resend any image");
  console.log("PASS: zero-AI capture upload, PNG/JPEG pixel validation, size limits, concurrent monotonic names, document isolation, traversal rejection, disk persistence, multi-image send, warm resume, failure, historical-image migration and idempotent committed-turn recovery.");
  globalThis.__getItDocumentAI = undefined;
  fs.rmSync(process.env.GETIT_DATA_DIR, { recursive: true, force: true });
}
main().catch(error => { console.error(error); process.exitCode = 1; });
